/********************************************************************************
** Form generated from reading UI file 'spells.ui'
**
** Created by: Qt User Interface Compiler version 5.0.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SPELLS_H
#define UI_SPELLS_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Spells
{
public:
    QPushButton *btnBack;
    QPushButton *btnNext;
    QTabWidget *tabWidget;
    QWidget *tabStr;
    QTableWidget *tableWidget;
    QLabel *label_3;
    QTextBrowser *textBrowser;
    QWidget *tabDexerity;
    QTextBrowser *textBrowser_2;
    QTableWidget *tableWidget_2;
    QLabel *label_4;
    QWidget *tabConstruction;
    QTableWidget *tableWidget_3;
    QLabel *label_5;
    QTextBrowser *textBrowser_3;
    QWidget *tabIntelligence;
    QTableWidget *tableWidget_4;
    QLabel *label_6;
    QTextBrowser *textBrowser_4;
    QWidget *tabWizdom;
    QTextBrowser *textBrowser_5;
    QTableWidget *tableWidget_5;
    QLabel *label_7;
    QWidget *tab;
    QTableWidget *tableWidget_6;
    QLabel *label_8;
    QTextBrowser *textBrowser_6;
    QWidget *tab_2;
    QTableWidget *tableWidget_7;
    QLabel *label_9;
    QTextBrowser *textBrowser_7;
    QWidget *tab_3;
    QTableWidget *tableWidget_8;
    QLabel *label_10;
    QTextBrowser *textBrowser_8;
    QWidget *tab_4;
    QTableWidget *tableWidget_9;
    QLabel *label_11;
    QTextBrowser *textBrowser_9;
    QLabel *lblTitle;
    QLabel *label_2;
    QLabel *label;
    QPushButton *btnAboutClasses;

    void setupUi(QWidget *Spells)
    {
        if (Spells->objectName().isEmpty())
            Spells->setObjectName(QStringLiteral("Spells"));
        Spells->resize(616, 513);
        btnBack = new QPushButton(Spells);
        btnBack->setObjectName(QStringLiteral("btnBack"));
        btnBack->setGeometry(QRect(357, 470, 114, 32));
        btnNext = new QPushButton(Spells);
        btnNext->setObjectName(QStringLiteral("btnNext"));
        btnNext->setGeometry(QRect(487, 470, 114, 32));
        tabWidget = new QTabWidget(Spells);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(20, 120, 581, 331));
        tabStr = new QWidget();
        tabStr->setObjectName(QStringLiteral("tabStr"));
        tableWidget = new QTableWidget(tabStr);
        if (tableWidget->columnCount() < 2)
            tableWidget->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        if (tableWidget->rowCount() < 7)
            tableWidget->setRowCount(7);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(0, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(1, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(2, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(3, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(4, __qtablewidgetitem6);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(5, __qtablewidgetitem7);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(6, __qtablewidgetitem8);
        QTableWidgetItem *__qtablewidgetitem9 = new QTableWidgetItem();
        tableWidget->setItem(0, 0, __qtablewidgetitem9);
        QTableWidgetItem *__qtablewidgetitem10 = new QTableWidgetItem();
        __qtablewidgetitem10->setCheckState(Qt::Unchecked);
        tableWidget->setItem(0, 1, __qtablewidgetitem10);
        QTableWidgetItem *__qtablewidgetitem11 = new QTableWidgetItem();
        tableWidget->setItem(1, 0, __qtablewidgetitem11);
        QTableWidgetItem *__qtablewidgetitem12 = new QTableWidgetItem();
        __qtablewidgetitem12->setCheckState(Qt::Unchecked);
        tableWidget->setItem(1, 1, __qtablewidgetitem12);
        QTableWidgetItem *__qtablewidgetitem13 = new QTableWidgetItem();
        tableWidget->setItem(2, 0, __qtablewidgetitem13);
        QTableWidgetItem *__qtablewidgetitem14 = new QTableWidgetItem();
        __qtablewidgetitem14->setCheckState(Qt::Unchecked);
        tableWidget->setItem(2, 1, __qtablewidgetitem14);
        QTableWidgetItem *__qtablewidgetitem15 = new QTableWidgetItem();
        tableWidget->setItem(3, 0, __qtablewidgetitem15);
        QTableWidgetItem *__qtablewidgetitem16 = new QTableWidgetItem();
        __qtablewidgetitem16->setCheckState(Qt::Unchecked);
        tableWidget->setItem(3, 1, __qtablewidgetitem16);
        QTableWidgetItem *__qtablewidgetitem17 = new QTableWidgetItem();
        tableWidget->setItem(4, 0, __qtablewidgetitem17);
        QTableWidgetItem *__qtablewidgetitem18 = new QTableWidgetItem();
        __qtablewidgetitem18->setCheckState(Qt::Unchecked);
        tableWidget->setItem(4, 1, __qtablewidgetitem18);
        QTableWidgetItem *__qtablewidgetitem19 = new QTableWidgetItem();
        tableWidget->setItem(5, 0, __qtablewidgetitem19);
        QTableWidgetItem *__qtablewidgetitem20 = new QTableWidgetItem();
        __qtablewidgetitem20->setCheckState(Qt::Unchecked);
        tableWidget->setItem(5, 1, __qtablewidgetitem20);
        QTableWidgetItem *__qtablewidgetitem21 = new QTableWidgetItem();
        tableWidget->setItem(6, 0, __qtablewidgetitem21);
        QTableWidgetItem *__qtablewidgetitem22 = new QTableWidgetItem();
        __qtablewidgetitem22->setCheckState(Qt::Unchecked);
        tableWidget->setItem(6, 1, __qtablewidgetitem22);
        tableWidget->setObjectName(QStringLiteral("tableWidget"));
        tableWidget->setGeometry(QRect(20, 10, 211, 271));
        label_3 = new QLabel(tabStr);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(240, 10, 121, 16));
        textBrowser = new QTextBrowser(tabStr);
        textBrowser->setObjectName(QStringLiteral("textBrowser"));
        textBrowser->setGeometry(QRect(240, 30, 321, 251));
        tabWidget->addTab(tabStr, QString());
        tabDexerity = new QWidget();
        tabDexerity->setObjectName(QStringLiteral("tabDexerity"));
        textBrowser_2 = new QTextBrowser(tabDexerity);
        textBrowser_2->setObjectName(QStringLiteral("textBrowser_2"));
        textBrowser_2->setGeometry(QRect(240, 30, 321, 251));
        tableWidget_2 = new QTableWidget(tabDexerity);
        if (tableWidget_2->columnCount() < 2)
            tableWidget_2->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem23 = new QTableWidgetItem();
        tableWidget_2->setHorizontalHeaderItem(0, __qtablewidgetitem23);
        QTableWidgetItem *__qtablewidgetitem24 = new QTableWidgetItem();
        tableWidget_2->setHorizontalHeaderItem(1, __qtablewidgetitem24);
        if (tableWidget_2->rowCount() < 7)
            tableWidget_2->setRowCount(7);
        QTableWidgetItem *__qtablewidgetitem25 = new QTableWidgetItem();
        tableWidget_2->setVerticalHeaderItem(0, __qtablewidgetitem25);
        QTableWidgetItem *__qtablewidgetitem26 = new QTableWidgetItem();
        tableWidget_2->setVerticalHeaderItem(1, __qtablewidgetitem26);
        QTableWidgetItem *__qtablewidgetitem27 = new QTableWidgetItem();
        tableWidget_2->setVerticalHeaderItem(2, __qtablewidgetitem27);
        QTableWidgetItem *__qtablewidgetitem28 = new QTableWidgetItem();
        tableWidget_2->setVerticalHeaderItem(3, __qtablewidgetitem28);
        QTableWidgetItem *__qtablewidgetitem29 = new QTableWidgetItem();
        tableWidget_2->setVerticalHeaderItem(4, __qtablewidgetitem29);
        QTableWidgetItem *__qtablewidgetitem30 = new QTableWidgetItem();
        tableWidget_2->setVerticalHeaderItem(5, __qtablewidgetitem30);
        QTableWidgetItem *__qtablewidgetitem31 = new QTableWidgetItem();
        tableWidget_2->setVerticalHeaderItem(6, __qtablewidgetitem31);
        QTableWidgetItem *__qtablewidgetitem32 = new QTableWidgetItem();
        tableWidget_2->setItem(0, 0, __qtablewidgetitem32);
        QTableWidgetItem *__qtablewidgetitem33 = new QTableWidgetItem();
        __qtablewidgetitem33->setCheckState(Qt::Unchecked);
        tableWidget_2->setItem(0, 1, __qtablewidgetitem33);
        QTableWidgetItem *__qtablewidgetitem34 = new QTableWidgetItem();
        tableWidget_2->setItem(1, 0, __qtablewidgetitem34);
        QTableWidgetItem *__qtablewidgetitem35 = new QTableWidgetItem();
        __qtablewidgetitem35->setCheckState(Qt::Unchecked);
        tableWidget_2->setItem(1, 1, __qtablewidgetitem35);
        QTableWidgetItem *__qtablewidgetitem36 = new QTableWidgetItem();
        tableWidget_2->setItem(2, 0, __qtablewidgetitem36);
        QTableWidgetItem *__qtablewidgetitem37 = new QTableWidgetItem();
        __qtablewidgetitem37->setCheckState(Qt::Unchecked);
        tableWidget_2->setItem(2, 1, __qtablewidgetitem37);
        QTableWidgetItem *__qtablewidgetitem38 = new QTableWidgetItem();
        tableWidget_2->setItem(3, 0, __qtablewidgetitem38);
        QTableWidgetItem *__qtablewidgetitem39 = new QTableWidgetItem();
        __qtablewidgetitem39->setCheckState(Qt::Unchecked);
        tableWidget_2->setItem(3, 1, __qtablewidgetitem39);
        QTableWidgetItem *__qtablewidgetitem40 = new QTableWidgetItem();
        tableWidget_2->setItem(4, 0, __qtablewidgetitem40);
        QTableWidgetItem *__qtablewidgetitem41 = new QTableWidgetItem();
        __qtablewidgetitem41->setCheckState(Qt::Unchecked);
        tableWidget_2->setItem(4, 1, __qtablewidgetitem41);
        QTableWidgetItem *__qtablewidgetitem42 = new QTableWidgetItem();
        tableWidget_2->setItem(5, 0, __qtablewidgetitem42);
        QTableWidgetItem *__qtablewidgetitem43 = new QTableWidgetItem();
        __qtablewidgetitem43->setCheckState(Qt::Unchecked);
        tableWidget_2->setItem(5, 1, __qtablewidgetitem43);
        QTableWidgetItem *__qtablewidgetitem44 = new QTableWidgetItem();
        tableWidget_2->setItem(6, 0, __qtablewidgetitem44);
        QTableWidgetItem *__qtablewidgetitem45 = new QTableWidgetItem();
        __qtablewidgetitem45->setCheckState(Qt::Unchecked);
        tableWidget_2->setItem(6, 1, __qtablewidgetitem45);
        tableWidget_2->setObjectName(QStringLiteral("tableWidget_2"));
        tableWidget_2->setGeometry(QRect(20, 10, 211, 271));
        label_4 = new QLabel(tabDexerity);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(240, 10, 121, 16));
        tabWidget->addTab(tabDexerity, QString());
        tabConstruction = new QWidget();
        tabConstruction->setObjectName(QStringLiteral("tabConstruction"));
        tableWidget_3 = new QTableWidget(tabConstruction);
        if (tableWidget_3->columnCount() < 2)
            tableWidget_3->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem46 = new QTableWidgetItem();
        tableWidget_3->setHorizontalHeaderItem(0, __qtablewidgetitem46);
        QTableWidgetItem *__qtablewidgetitem47 = new QTableWidgetItem();
        tableWidget_3->setHorizontalHeaderItem(1, __qtablewidgetitem47);
        if (tableWidget_3->rowCount() < 7)
            tableWidget_3->setRowCount(7);
        QTableWidgetItem *__qtablewidgetitem48 = new QTableWidgetItem();
        tableWidget_3->setVerticalHeaderItem(0, __qtablewidgetitem48);
        QTableWidgetItem *__qtablewidgetitem49 = new QTableWidgetItem();
        tableWidget_3->setVerticalHeaderItem(1, __qtablewidgetitem49);
        QTableWidgetItem *__qtablewidgetitem50 = new QTableWidgetItem();
        tableWidget_3->setVerticalHeaderItem(2, __qtablewidgetitem50);
        QTableWidgetItem *__qtablewidgetitem51 = new QTableWidgetItem();
        tableWidget_3->setVerticalHeaderItem(3, __qtablewidgetitem51);
        QTableWidgetItem *__qtablewidgetitem52 = new QTableWidgetItem();
        tableWidget_3->setVerticalHeaderItem(4, __qtablewidgetitem52);
        QTableWidgetItem *__qtablewidgetitem53 = new QTableWidgetItem();
        tableWidget_3->setVerticalHeaderItem(5, __qtablewidgetitem53);
        QTableWidgetItem *__qtablewidgetitem54 = new QTableWidgetItem();
        tableWidget_3->setVerticalHeaderItem(6, __qtablewidgetitem54);
        QTableWidgetItem *__qtablewidgetitem55 = new QTableWidgetItem();
        tableWidget_3->setItem(0, 0, __qtablewidgetitem55);
        QTableWidgetItem *__qtablewidgetitem56 = new QTableWidgetItem();
        __qtablewidgetitem56->setCheckState(Qt::Unchecked);
        tableWidget_3->setItem(0, 1, __qtablewidgetitem56);
        QTableWidgetItem *__qtablewidgetitem57 = new QTableWidgetItem();
        tableWidget_3->setItem(1, 0, __qtablewidgetitem57);
        QTableWidgetItem *__qtablewidgetitem58 = new QTableWidgetItem();
        __qtablewidgetitem58->setCheckState(Qt::Unchecked);
        tableWidget_3->setItem(1, 1, __qtablewidgetitem58);
        QTableWidgetItem *__qtablewidgetitem59 = new QTableWidgetItem();
        tableWidget_3->setItem(2, 0, __qtablewidgetitem59);
        QTableWidgetItem *__qtablewidgetitem60 = new QTableWidgetItem();
        __qtablewidgetitem60->setCheckState(Qt::Unchecked);
        tableWidget_3->setItem(2, 1, __qtablewidgetitem60);
        QTableWidgetItem *__qtablewidgetitem61 = new QTableWidgetItem();
        tableWidget_3->setItem(3, 0, __qtablewidgetitem61);
        QTableWidgetItem *__qtablewidgetitem62 = new QTableWidgetItem();
        __qtablewidgetitem62->setCheckState(Qt::Unchecked);
        tableWidget_3->setItem(3, 1, __qtablewidgetitem62);
        QTableWidgetItem *__qtablewidgetitem63 = new QTableWidgetItem();
        tableWidget_3->setItem(4, 0, __qtablewidgetitem63);
        QTableWidgetItem *__qtablewidgetitem64 = new QTableWidgetItem();
        __qtablewidgetitem64->setCheckState(Qt::Unchecked);
        tableWidget_3->setItem(4, 1, __qtablewidgetitem64);
        QTableWidgetItem *__qtablewidgetitem65 = new QTableWidgetItem();
        tableWidget_3->setItem(5, 0, __qtablewidgetitem65);
        QTableWidgetItem *__qtablewidgetitem66 = new QTableWidgetItem();
        __qtablewidgetitem66->setCheckState(Qt::Unchecked);
        tableWidget_3->setItem(5, 1, __qtablewidgetitem66);
        QTableWidgetItem *__qtablewidgetitem67 = new QTableWidgetItem();
        tableWidget_3->setItem(6, 0, __qtablewidgetitem67);
        QTableWidgetItem *__qtablewidgetitem68 = new QTableWidgetItem();
        __qtablewidgetitem68->setCheckState(Qt::Unchecked);
        tableWidget_3->setItem(6, 1, __qtablewidgetitem68);
        tableWidget_3->setObjectName(QStringLiteral("tableWidget_3"));
        tableWidget_3->setGeometry(QRect(20, 10, 211, 271));
        label_5 = new QLabel(tabConstruction);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(240, 10, 121, 16));
        textBrowser_3 = new QTextBrowser(tabConstruction);
        textBrowser_3->setObjectName(QStringLiteral("textBrowser_3"));
        textBrowser_3->setGeometry(QRect(240, 30, 321, 251));
        tabWidget->addTab(tabConstruction, QString());
        tabIntelligence = new QWidget();
        tabIntelligence->setObjectName(QStringLiteral("tabIntelligence"));
        tableWidget_4 = new QTableWidget(tabIntelligence);
        if (tableWidget_4->columnCount() < 2)
            tableWidget_4->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem69 = new QTableWidgetItem();
        tableWidget_4->setHorizontalHeaderItem(0, __qtablewidgetitem69);
        QTableWidgetItem *__qtablewidgetitem70 = new QTableWidgetItem();
        tableWidget_4->setHorizontalHeaderItem(1, __qtablewidgetitem70);
        if (tableWidget_4->rowCount() < 7)
            tableWidget_4->setRowCount(7);
        QTableWidgetItem *__qtablewidgetitem71 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(0, __qtablewidgetitem71);
        QTableWidgetItem *__qtablewidgetitem72 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(1, __qtablewidgetitem72);
        QTableWidgetItem *__qtablewidgetitem73 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(2, __qtablewidgetitem73);
        QTableWidgetItem *__qtablewidgetitem74 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(3, __qtablewidgetitem74);
        QTableWidgetItem *__qtablewidgetitem75 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(4, __qtablewidgetitem75);
        QTableWidgetItem *__qtablewidgetitem76 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(5, __qtablewidgetitem76);
        QTableWidgetItem *__qtablewidgetitem77 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(6, __qtablewidgetitem77);
        QTableWidgetItem *__qtablewidgetitem78 = new QTableWidgetItem();
        tableWidget_4->setItem(0, 0, __qtablewidgetitem78);
        QTableWidgetItem *__qtablewidgetitem79 = new QTableWidgetItem();
        __qtablewidgetitem79->setCheckState(Qt::Unchecked);
        tableWidget_4->setItem(0, 1, __qtablewidgetitem79);
        QTableWidgetItem *__qtablewidgetitem80 = new QTableWidgetItem();
        tableWidget_4->setItem(1, 0, __qtablewidgetitem80);
        QTableWidgetItem *__qtablewidgetitem81 = new QTableWidgetItem();
        __qtablewidgetitem81->setCheckState(Qt::Unchecked);
        tableWidget_4->setItem(1, 1, __qtablewidgetitem81);
        QTableWidgetItem *__qtablewidgetitem82 = new QTableWidgetItem();
        tableWidget_4->setItem(2, 0, __qtablewidgetitem82);
        QTableWidgetItem *__qtablewidgetitem83 = new QTableWidgetItem();
        __qtablewidgetitem83->setCheckState(Qt::Unchecked);
        tableWidget_4->setItem(2, 1, __qtablewidgetitem83);
        QTableWidgetItem *__qtablewidgetitem84 = new QTableWidgetItem();
        tableWidget_4->setItem(3, 0, __qtablewidgetitem84);
        QTableWidgetItem *__qtablewidgetitem85 = new QTableWidgetItem();
        __qtablewidgetitem85->setCheckState(Qt::Unchecked);
        tableWidget_4->setItem(3, 1, __qtablewidgetitem85);
        QTableWidgetItem *__qtablewidgetitem86 = new QTableWidgetItem();
        tableWidget_4->setItem(4, 0, __qtablewidgetitem86);
        QTableWidgetItem *__qtablewidgetitem87 = new QTableWidgetItem();
        __qtablewidgetitem87->setCheckState(Qt::Unchecked);
        tableWidget_4->setItem(4, 1, __qtablewidgetitem87);
        QTableWidgetItem *__qtablewidgetitem88 = new QTableWidgetItem();
        tableWidget_4->setItem(5, 0, __qtablewidgetitem88);
        QTableWidgetItem *__qtablewidgetitem89 = new QTableWidgetItem();
        __qtablewidgetitem89->setCheckState(Qt::Unchecked);
        tableWidget_4->setItem(5, 1, __qtablewidgetitem89);
        QTableWidgetItem *__qtablewidgetitem90 = new QTableWidgetItem();
        tableWidget_4->setItem(6, 0, __qtablewidgetitem90);
        QTableWidgetItem *__qtablewidgetitem91 = new QTableWidgetItem();
        __qtablewidgetitem91->setCheckState(Qt::Unchecked);
        tableWidget_4->setItem(6, 1, __qtablewidgetitem91);
        tableWidget_4->setObjectName(QStringLiteral("tableWidget_4"));
        tableWidget_4->setGeometry(QRect(20, 10, 211, 271));
        label_6 = new QLabel(tabIntelligence);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(240, 10, 121, 16));
        textBrowser_4 = new QTextBrowser(tabIntelligence);
        textBrowser_4->setObjectName(QStringLiteral("textBrowser_4"));
        textBrowser_4->setGeometry(QRect(240, 30, 321, 251));
        tabWidget->addTab(tabIntelligence, QString());
        tabWizdom = new QWidget();
        tabWizdom->setObjectName(QStringLiteral("tabWizdom"));
        textBrowser_5 = new QTextBrowser(tabWizdom);
        textBrowser_5->setObjectName(QStringLiteral("textBrowser_5"));
        textBrowser_5->setGeometry(QRect(240, 30, 321, 251));
        tableWidget_5 = new QTableWidget(tabWizdom);
        if (tableWidget_5->columnCount() < 2)
            tableWidget_5->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem92 = new QTableWidgetItem();
        tableWidget_5->setHorizontalHeaderItem(0, __qtablewidgetitem92);
        QTableWidgetItem *__qtablewidgetitem93 = new QTableWidgetItem();
        tableWidget_5->setHorizontalHeaderItem(1, __qtablewidgetitem93);
        if (tableWidget_5->rowCount() < 7)
            tableWidget_5->setRowCount(7);
        QTableWidgetItem *__qtablewidgetitem94 = new QTableWidgetItem();
        tableWidget_5->setVerticalHeaderItem(0, __qtablewidgetitem94);
        QTableWidgetItem *__qtablewidgetitem95 = new QTableWidgetItem();
        tableWidget_5->setVerticalHeaderItem(1, __qtablewidgetitem95);
        QTableWidgetItem *__qtablewidgetitem96 = new QTableWidgetItem();
        tableWidget_5->setVerticalHeaderItem(2, __qtablewidgetitem96);
        QTableWidgetItem *__qtablewidgetitem97 = new QTableWidgetItem();
        tableWidget_5->setVerticalHeaderItem(3, __qtablewidgetitem97);
        QTableWidgetItem *__qtablewidgetitem98 = new QTableWidgetItem();
        tableWidget_5->setVerticalHeaderItem(4, __qtablewidgetitem98);
        QTableWidgetItem *__qtablewidgetitem99 = new QTableWidgetItem();
        tableWidget_5->setVerticalHeaderItem(5, __qtablewidgetitem99);
        QTableWidgetItem *__qtablewidgetitem100 = new QTableWidgetItem();
        tableWidget_5->setVerticalHeaderItem(6, __qtablewidgetitem100);
        QTableWidgetItem *__qtablewidgetitem101 = new QTableWidgetItem();
        tableWidget_5->setItem(0, 0, __qtablewidgetitem101);
        QTableWidgetItem *__qtablewidgetitem102 = new QTableWidgetItem();
        __qtablewidgetitem102->setCheckState(Qt::Unchecked);
        tableWidget_5->setItem(0, 1, __qtablewidgetitem102);
        QTableWidgetItem *__qtablewidgetitem103 = new QTableWidgetItem();
        tableWidget_5->setItem(1, 0, __qtablewidgetitem103);
        QTableWidgetItem *__qtablewidgetitem104 = new QTableWidgetItem();
        __qtablewidgetitem104->setCheckState(Qt::Unchecked);
        tableWidget_5->setItem(1, 1, __qtablewidgetitem104);
        QTableWidgetItem *__qtablewidgetitem105 = new QTableWidgetItem();
        tableWidget_5->setItem(2, 0, __qtablewidgetitem105);
        QTableWidgetItem *__qtablewidgetitem106 = new QTableWidgetItem();
        __qtablewidgetitem106->setCheckState(Qt::Unchecked);
        tableWidget_5->setItem(2, 1, __qtablewidgetitem106);
        QTableWidgetItem *__qtablewidgetitem107 = new QTableWidgetItem();
        tableWidget_5->setItem(3, 0, __qtablewidgetitem107);
        QTableWidgetItem *__qtablewidgetitem108 = new QTableWidgetItem();
        __qtablewidgetitem108->setCheckState(Qt::Unchecked);
        tableWidget_5->setItem(3, 1, __qtablewidgetitem108);
        QTableWidgetItem *__qtablewidgetitem109 = new QTableWidgetItem();
        tableWidget_5->setItem(4, 0, __qtablewidgetitem109);
        QTableWidgetItem *__qtablewidgetitem110 = new QTableWidgetItem();
        __qtablewidgetitem110->setCheckState(Qt::Unchecked);
        tableWidget_5->setItem(4, 1, __qtablewidgetitem110);
        QTableWidgetItem *__qtablewidgetitem111 = new QTableWidgetItem();
        tableWidget_5->setItem(5, 0, __qtablewidgetitem111);
        QTableWidgetItem *__qtablewidgetitem112 = new QTableWidgetItem();
        __qtablewidgetitem112->setCheckState(Qt::Unchecked);
        tableWidget_5->setItem(5, 1, __qtablewidgetitem112);
        QTableWidgetItem *__qtablewidgetitem113 = new QTableWidgetItem();
        tableWidget_5->setItem(6, 0, __qtablewidgetitem113);
        QTableWidgetItem *__qtablewidgetitem114 = new QTableWidgetItem();
        __qtablewidgetitem114->setCheckState(Qt::Unchecked);
        tableWidget_5->setItem(6, 1, __qtablewidgetitem114);
        tableWidget_5->setObjectName(QStringLiteral("tableWidget_5"));
        tableWidget_5->setGeometry(QRect(20, 10, 211, 271));
        label_7 = new QLabel(tabWizdom);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(240, 10, 121, 16));
        tabWidget->addTab(tabWizdom, QString());
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        tableWidget_6 = new QTableWidget(tab);
        if (tableWidget_6->columnCount() < 2)
            tableWidget_6->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem115 = new QTableWidgetItem();
        tableWidget_6->setHorizontalHeaderItem(0, __qtablewidgetitem115);
        QTableWidgetItem *__qtablewidgetitem116 = new QTableWidgetItem();
        tableWidget_6->setHorizontalHeaderItem(1, __qtablewidgetitem116);
        if (tableWidget_6->rowCount() < 7)
            tableWidget_6->setRowCount(7);
        QTableWidgetItem *__qtablewidgetitem117 = new QTableWidgetItem();
        tableWidget_6->setVerticalHeaderItem(0, __qtablewidgetitem117);
        QTableWidgetItem *__qtablewidgetitem118 = new QTableWidgetItem();
        tableWidget_6->setVerticalHeaderItem(1, __qtablewidgetitem118);
        QTableWidgetItem *__qtablewidgetitem119 = new QTableWidgetItem();
        tableWidget_6->setVerticalHeaderItem(2, __qtablewidgetitem119);
        QTableWidgetItem *__qtablewidgetitem120 = new QTableWidgetItem();
        tableWidget_6->setVerticalHeaderItem(3, __qtablewidgetitem120);
        QTableWidgetItem *__qtablewidgetitem121 = new QTableWidgetItem();
        tableWidget_6->setVerticalHeaderItem(4, __qtablewidgetitem121);
        QTableWidgetItem *__qtablewidgetitem122 = new QTableWidgetItem();
        tableWidget_6->setVerticalHeaderItem(5, __qtablewidgetitem122);
        QTableWidgetItem *__qtablewidgetitem123 = new QTableWidgetItem();
        tableWidget_6->setVerticalHeaderItem(6, __qtablewidgetitem123);
        QTableWidgetItem *__qtablewidgetitem124 = new QTableWidgetItem();
        tableWidget_6->setItem(0, 0, __qtablewidgetitem124);
        QTableWidgetItem *__qtablewidgetitem125 = new QTableWidgetItem();
        __qtablewidgetitem125->setCheckState(Qt::Unchecked);
        tableWidget_6->setItem(0, 1, __qtablewidgetitem125);
        QTableWidgetItem *__qtablewidgetitem126 = new QTableWidgetItem();
        tableWidget_6->setItem(1, 0, __qtablewidgetitem126);
        QTableWidgetItem *__qtablewidgetitem127 = new QTableWidgetItem();
        __qtablewidgetitem127->setCheckState(Qt::Unchecked);
        tableWidget_6->setItem(1, 1, __qtablewidgetitem127);
        QTableWidgetItem *__qtablewidgetitem128 = new QTableWidgetItem();
        tableWidget_6->setItem(2, 0, __qtablewidgetitem128);
        QTableWidgetItem *__qtablewidgetitem129 = new QTableWidgetItem();
        __qtablewidgetitem129->setCheckState(Qt::Unchecked);
        tableWidget_6->setItem(2, 1, __qtablewidgetitem129);
        QTableWidgetItem *__qtablewidgetitem130 = new QTableWidgetItem();
        tableWidget_6->setItem(3, 0, __qtablewidgetitem130);
        QTableWidgetItem *__qtablewidgetitem131 = new QTableWidgetItem();
        __qtablewidgetitem131->setCheckState(Qt::Unchecked);
        tableWidget_6->setItem(3, 1, __qtablewidgetitem131);
        QTableWidgetItem *__qtablewidgetitem132 = new QTableWidgetItem();
        tableWidget_6->setItem(4, 0, __qtablewidgetitem132);
        QTableWidgetItem *__qtablewidgetitem133 = new QTableWidgetItem();
        __qtablewidgetitem133->setCheckState(Qt::Unchecked);
        tableWidget_6->setItem(4, 1, __qtablewidgetitem133);
        QTableWidgetItem *__qtablewidgetitem134 = new QTableWidgetItem();
        tableWidget_6->setItem(5, 0, __qtablewidgetitem134);
        QTableWidgetItem *__qtablewidgetitem135 = new QTableWidgetItem();
        __qtablewidgetitem135->setCheckState(Qt::Unchecked);
        tableWidget_6->setItem(5, 1, __qtablewidgetitem135);
        QTableWidgetItem *__qtablewidgetitem136 = new QTableWidgetItem();
        tableWidget_6->setItem(6, 0, __qtablewidgetitem136);
        QTableWidgetItem *__qtablewidgetitem137 = new QTableWidgetItem();
        __qtablewidgetitem137->setCheckState(Qt::Unchecked);
        tableWidget_6->setItem(6, 1, __qtablewidgetitem137);
        tableWidget_6->setObjectName(QStringLiteral("tableWidget_6"));
        tableWidget_6->setGeometry(QRect(20, 10, 211, 271));
        label_8 = new QLabel(tab);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(240, 10, 121, 16));
        textBrowser_6 = new QTextBrowser(tab);
        textBrowser_6->setObjectName(QStringLiteral("textBrowser_6"));
        textBrowser_6->setGeometry(QRect(240, 30, 321, 251));
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        tableWidget_7 = new QTableWidget(tab_2);
        if (tableWidget_7->columnCount() < 2)
            tableWidget_7->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem138 = new QTableWidgetItem();
        tableWidget_7->setHorizontalHeaderItem(0, __qtablewidgetitem138);
        QTableWidgetItem *__qtablewidgetitem139 = new QTableWidgetItem();
        tableWidget_7->setHorizontalHeaderItem(1, __qtablewidgetitem139);
        if (tableWidget_7->rowCount() < 7)
            tableWidget_7->setRowCount(7);
        QTableWidgetItem *__qtablewidgetitem140 = new QTableWidgetItem();
        tableWidget_7->setVerticalHeaderItem(0, __qtablewidgetitem140);
        QTableWidgetItem *__qtablewidgetitem141 = new QTableWidgetItem();
        tableWidget_7->setVerticalHeaderItem(1, __qtablewidgetitem141);
        QTableWidgetItem *__qtablewidgetitem142 = new QTableWidgetItem();
        tableWidget_7->setVerticalHeaderItem(2, __qtablewidgetitem142);
        QTableWidgetItem *__qtablewidgetitem143 = new QTableWidgetItem();
        tableWidget_7->setVerticalHeaderItem(3, __qtablewidgetitem143);
        QTableWidgetItem *__qtablewidgetitem144 = new QTableWidgetItem();
        tableWidget_7->setVerticalHeaderItem(4, __qtablewidgetitem144);
        QTableWidgetItem *__qtablewidgetitem145 = new QTableWidgetItem();
        tableWidget_7->setVerticalHeaderItem(5, __qtablewidgetitem145);
        QTableWidgetItem *__qtablewidgetitem146 = new QTableWidgetItem();
        tableWidget_7->setVerticalHeaderItem(6, __qtablewidgetitem146);
        QTableWidgetItem *__qtablewidgetitem147 = new QTableWidgetItem();
        tableWidget_7->setItem(0, 0, __qtablewidgetitem147);
        QTableWidgetItem *__qtablewidgetitem148 = new QTableWidgetItem();
        __qtablewidgetitem148->setCheckState(Qt::Unchecked);
        tableWidget_7->setItem(0, 1, __qtablewidgetitem148);
        QTableWidgetItem *__qtablewidgetitem149 = new QTableWidgetItem();
        tableWidget_7->setItem(1, 0, __qtablewidgetitem149);
        QTableWidgetItem *__qtablewidgetitem150 = new QTableWidgetItem();
        __qtablewidgetitem150->setCheckState(Qt::Unchecked);
        tableWidget_7->setItem(1, 1, __qtablewidgetitem150);
        QTableWidgetItem *__qtablewidgetitem151 = new QTableWidgetItem();
        tableWidget_7->setItem(2, 0, __qtablewidgetitem151);
        QTableWidgetItem *__qtablewidgetitem152 = new QTableWidgetItem();
        __qtablewidgetitem152->setCheckState(Qt::Unchecked);
        tableWidget_7->setItem(2, 1, __qtablewidgetitem152);
        QTableWidgetItem *__qtablewidgetitem153 = new QTableWidgetItem();
        tableWidget_7->setItem(3, 0, __qtablewidgetitem153);
        QTableWidgetItem *__qtablewidgetitem154 = new QTableWidgetItem();
        __qtablewidgetitem154->setCheckState(Qt::Unchecked);
        tableWidget_7->setItem(3, 1, __qtablewidgetitem154);
        QTableWidgetItem *__qtablewidgetitem155 = new QTableWidgetItem();
        tableWidget_7->setItem(4, 0, __qtablewidgetitem155);
        QTableWidgetItem *__qtablewidgetitem156 = new QTableWidgetItem();
        __qtablewidgetitem156->setCheckState(Qt::Unchecked);
        tableWidget_7->setItem(4, 1, __qtablewidgetitem156);
        QTableWidgetItem *__qtablewidgetitem157 = new QTableWidgetItem();
        tableWidget_7->setItem(5, 0, __qtablewidgetitem157);
        QTableWidgetItem *__qtablewidgetitem158 = new QTableWidgetItem();
        __qtablewidgetitem158->setCheckState(Qt::Unchecked);
        tableWidget_7->setItem(5, 1, __qtablewidgetitem158);
        QTableWidgetItem *__qtablewidgetitem159 = new QTableWidgetItem();
        tableWidget_7->setItem(6, 0, __qtablewidgetitem159);
        QTableWidgetItem *__qtablewidgetitem160 = new QTableWidgetItem();
        __qtablewidgetitem160->setCheckState(Qt::Unchecked);
        tableWidget_7->setItem(6, 1, __qtablewidgetitem160);
        tableWidget_7->setObjectName(QStringLiteral("tableWidget_7"));
        tableWidget_7->setGeometry(QRect(20, 10, 211, 271));
        label_9 = new QLabel(tab_2);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(240, 10, 121, 16));
        textBrowser_7 = new QTextBrowser(tab_2);
        textBrowser_7->setObjectName(QStringLiteral("textBrowser_7"));
        textBrowser_7->setGeometry(QRect(240, 30, 321, 251));
        tabWidget->addTab(tab_2, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        tableWidget_8 = new QTableWidget(tab_3);
        if (tableWidget_8->columnCount() < 2)
            tableWidget_8->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem161 = new QTableWidgetItem();
        tableWidget_8->setHorizontalHeaderItem(0, __qtablewidgetitem161);
        QTableWidgetItem *__qtablewidgetitem162 = new QTableWidgetItem();
        tableWidget_8->setHorizontalHeaderItem(1, __qtablewidgetitem162);
        if (tableWidget_8->rowCount() < 7)
            tableWidget_8->setRowCount(7);
        QTableWidgetItem *__qtablewidgetitem163 = new QTableWidgetItem();
        tableWidget_8->setVerticalHeaderItem(0, __qtablewidgetitem163);
        QTableWidgetItem *__qtablewidgetitem164 = new QTableWidgetItem();
        tableWidget_8->setVerticalHeaderItem(1, __qtablewidgetitem164);
        QTableWidgetItem *__qtablewidgetitem165 = new QTableWidgetItem();
        tableWidget_8->setVerticalHeaderItem(2, __qtablewidgetitem165);
        QTableWidgetItem *__qtablewidgetitem166 = new QTableWidgetItem();
        tableWidget_8->setVerticalHeaderItem(3, __qtablewidgetitem166);
        QTableWidgetItem *__qtablewidgetitem167 = new QTableWidgetItem();
        tableWidget_8->setVerticalHeaderItem(4, __qtablewidgetitem167);
        QTableWidgetItem *__qtablewidgetitem168 = new QTableWidgetItem();
        tableWidget_8->setVerticalHeaderItem(5, __qtablewidgetitem168);
        QTableWidgetItem *__qtablewidgetitem169 = new QTableWidgetItem();
        tableWidget_8->setVerticalHeaderItem(6, __qtablewidgetitem169);
        QTableWidgetItem *__qtablewidgetitem170 = new QTableWidgetItem();
        tableWidget_8->setItem(0, 0, __qtablewidgetitem170);
        QTableWidgetItem *__qtablewidgetitem171 = new QTableWidgetItem();
        __qtablewidgetitem171->setCheckState(Qt::Unchecked);
        tableWidget_8->setItem(0, 1, __qtablewidgetitem171);
        QTableWidgetItem *__qtablewidgetitem172 = new QTableWidgetItem();
        tableWidget_8->setItem(1, 0, __qtablewidgetitem172);
        QTableWidgetItem *__qtablewidgetitem173 = new QTableWidgetItem();
        __qtablewidgetitem173->setCheckState(Qt::Unchecked);
        tableWidget_8->setItem(1, 1, __qtablewidgetitem173);
        QTableWidgetItem *__qtablewidgetitem174 = new QTableWidgetItem();
        tableWidget_8->setItem(2, 0, __qtablewidgetitem174);
        QTableWidgetItem *__qtablewidgetitem175 = new QTableWidgetItem();
        __qtablewidgetitem175->setCheckState(Qt::Unchecked);
        tableWidget_8->setItem(2, 1, __qtablewidgetitem175);
        QTableWidgetItem *__qtablewidgetitem176 = new QTableWidgetItem();
        tableWidget_8->setItem(3, 0, __qtablewidgetitem176);
        QTableWidgetItem *__qtablewidgetitem177 = new QTableWidgetItem();
        __qtablewidgetitem177->setCheckState(Qt::Unchecked);
        tableWidget_8->setItem(3, 1, __qtablewidgetitem177);
        QTableWidgetItem *__qtablewidgetitem178 = new QTableWidgetItem();
        tableWidget_8->setItem(4, 0, __qtablewidgetitem178);
        QTableWidgetItem *__qtablewidgetitem179 = new QTableWidgetItem();
        __qtablewidgetitem179->setCheckState(Qt::Unchecked);
        tableWidget_8->setItem(4, 1, __qtablewidgetitem179);
        QTableWidgetItem *__qtablewidgetitem180 = new QTableWidgetItem();
        tableWidget_8->setItem(5, 0, __qtablewidgetitem180);
        QTableWidgetItem *__qtablewidgetitem181 = new QTableWidgetItem();
        __qtablewidgetitem181->setCheckState(Qt::Unchecked);
        tableWidget_8->setItem(5, 1, __qtablewidgetitem181);
        QTableWidgetItem *__qtablewidgetitem182 = new QTableWidgetItem();
        tableWidget_8->setItem(6, 0, __qtablewidgetitem182);
        QTableWidgetItem *__qtablewidgetitem183 = new QTableWidgetItem();
        __qtablewidgetitem183->setCheckState(Qt::Unchecked);
        tableWidget_8->setItem(6, 1, __qtablewidgetitem183);
        tableWidget_8->setObjectName(QStringLiteral("tableWidget_8"));
        tableWidget_8->setGeometry(QRect(20, 10, 211, 271));
        label_10 = new QLabel(tab_3);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(240, 10, 121, 16));
        textBrowser_8 = new QTextBrowser(tab_3);
        textBrowser_8->setObjectName(QStringLiteral("textBrowser_8"));
        textBrowser_8->setGeometry(QRect(240, 30, 321, 251));
        tabWidget->addTab(tab_3, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QStringLiteral("tab_4"));
        tableWidget_9 = new QTableWidget(tab_4);
        if (tableWidget_9->columnCount() < 2)
            tableWidget_9->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem184 = new QTableWidgetItem();
        tableWidget_9->setHorizontalHeaderItem(0, __qtablewidgetitem184);
        QTableWidgetItem *__qtablewidgetitem185 = new QTableWidgetItem();
        tableWidget_9->setHorizontalHeaderItem(1, __qtablewidgetitem185);
        if (tableWidget_9->rowCount() < 7)
            tableWidget_9->setRowCount(7);
        QTableWidgetItem *__qtablewidgetitem186 = new QTableWidgetItem();
        tableWidget_9->setVerticalHeaderItem(0, __qtablewidgetitem186);
        QTableWidgetItem *__qtablewidgetitem187 = new QTableWidgetItem();
        tableWidget_9->setVerticalHeaderItem(1, __qtablewidgetitem187);
        QTableWidgetItem *__qtablewidgetitem188 = new QTableWidgetItem();
        tableWidget_9->setVerticalHeaderItem(2, __qtablewidgetitem188);
        QTableWidgetItem *__qtablewidgetitem189 = new QTableWidgetItem();
        tableWidget_9->setVerticalHeaderItem(3, __qtablewidgetitem189);
        QTableWidgetItem *__qtablewidgetitem190 = new QTableWidgetItem();
        tableWidget_9->setVerticalHeaderItem(4, __qtablewidgetitem190);
        QTableWidgetItem *__qtablewidgetitem191 = new QTableWidgetItem();
        tableWidget_9->setVerticalHeaderItem(5, __qtablewidgetitem191);
        QTableWidgetItem *__qtablewidgetitem192 = new QTableWidgetItem();
        tableWidget_9->setVerticalHeaderItem(6, __qtablewidgetitem192);
        QTableWidgetItem *__qtablewidgetitem193 = new QTableWidgetItem();
        tableWidget_9->setItem(0, 0, __qtablewidgetitem193);
        QTableWidgetItem *__qtablewidgetitem194 = new QTableWidgetItem();
        __qtablewidgetitem194->setCheckState(Qt::Unchecked);
        tableWidget_9->setItem(0, 1, __qtablewidgetitem194);
        QTableWidgetItem *__qtablewidgetitem195 = new QTableWidgetItem();
        tableWidget_9->setItem(1, 0, __qtablewidgetitem195);
        QTableWidgetItem *__qtablewidgetitem196 = new QTableWidgetItem();
        __qtablewidgetitem196->setCheckState(Qt::Unchecked);
        tableWidget_9->setItem(1, 1, __qtablewidgetitem196);
        QTableWidgetItem *__qtablewidgetitem197 = new QTableWidgetItem();
        tableWidget_9->setItem(2, 0, __qtablewidgetitem197);
        QTableWidgetItem *__qtablewidgetitem198 = new QTableWidgetItem();
        __qtablewidgetitem198->setCheckState(Qt::Unchecked);
        tableWidget_9->setItem(2, 1, __qtablewidgetitem198);
        QTableWidgetItem *__qtablewidgetitem199 = new QTableWidgetItem();
        tableWidget_9->setItem(3, 0, __qtablewidgetitem199);
        QTableWidgetItem *__qtablewidgetitem200 = new QTableWidgetItem();
        __qtablewidgetitem200->setCheckState(Qt::Unchecked);
        tableWidget_9->setItem(3, 1, __qtablewidgetitem200);
        QTableWidgetItem *__qtablewidgetitem201 = new QTableWidgetItem();
        tableWidget_9->setItem(4, 0, __qtablewidgetitem201);
        QTableWidgetItem *__qtablewidgetitem202 = new QTableWidgetItem();
        __qtablewidgetitem202->setCheckState(Qt::Unchecked);
        tableWidget_9->setItem(4, 1, __qtablewidgetitem202);
        QTableWidgetItem *__qtablewidgetitem203 = new QTableWidgetItem();
        tableWidget_9->setItem(5, 0, __qtablewidgetitem203);
        QTableWidgetItem *__qtablewidgetitem204 = new QTableWidgetItem();
        __qtablewidgetitem204->setCheckState(Qt::Unchecked);
        tableWidget_9->setItem(5, 1, __qtablewidgetitem204);
        QTableWidgetItem *__qtablewidgetitem205 = new QTableWidgetItem();
        tableWidget_9->setItem(6, 0, __qtablewidgetitem205);
        QTableWidgetItem *__qtablewidgetitem206 = new QTableWidgetItem();
        __qtablewidgetitem206->setCheckState(Qt::Unchecked);
        tableWidget_9->setItem(6, 1, __qtablewidgetitem206);
        tableWidget_9->setObjectName(QStringLiteral("tableWidget_9"));
        tableWidget_9->setGeometry(QRect(20, 10, 211, 271));
        label_11 = new QLabel(tab_4);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(240, 10, 121, 16));
        textBrowser_9 = new QTextBrowser(tab_4);
        textBrowser_9->setObjectName(QStringLiteral("textBrowser_9"));
        textBrowser_9->setGeometry(QRect(240, 30, 321, 251));
        tabWidget->addTab(tab_4, QString());
        lblTitle = new QLabel(Spells);
        lblTitle->setObjectName(QStringLiteral("lblTitle"));
        lblTitle->setGeometry(QRect(17, 10, 201, 41));
        QFont font;
        font.setFamily(QStringLiteral("Arial"));
        font.setPointSize(34);
        lblTitle->setFont(font);
        label_2 = new QLabel(Spells);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(210, 70, 62, 21));
        QFont font1;
        font1.setFamily(QStringLiteral("Arial"));
        font1.setPointSize(16);
        label_2->setFont(font1);
        label = new QLabel(Spells);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(27, 70, 181, 21));
        label->setFont(font1);
        btnAboutClasses = new QPushButton(Spells);
        btnAboutClasses->setObjectName(QStringLiteral("btnAboutClasses"));
        btnAboutClasses->setGeometry(QRect(450, 10, 151, 32));

        retranslateUi(Spells);

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(Spells);
    } // setupUi

    void retranslateUi(QWidget *Spells)
    {
        Spells->setWindowTitle(QApplication::translate("Spells", "Form", 0));
        btnBack->setText(QApplication::translate("Spells", "Back", 0));
        btnNext->setText(QApplication::translate("Spells", "Next", 0));
        QTableWidgetItem *___qtablewidgetitem = tableWidget->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QApplication::translate("Spells", "Name", 0));
        QTableWidgetItem *___qtablewidgetitem1 = tableWidget->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QApplication::translate("Spells", "Learned", 0));

        const bool __sortingEnabled = tableWidget->isSortingEnabled();
        tableWidget->setSortingEnabled(false);
        QTableWidgetItem *___qtablewidgetitem2 = tableWidget->item(0, 0);
        ___qtablewidgetitem2->setText(QApplication::translate("Spells", "Jump", 0));
        QTableWidgetItem *___qtablewidgetitem3 = tableWidget->item(1, 0);
        ___qtablewidgetitem3->setText(QApplication::translate("Spells", "Alarm", 0));
        QTableWidgetItem *___qtablewidgetitem4 = tableWidget->item(2, 0);
        ___qtablewidgetitem4->setText(QApplication::translate("Spells", "Shield", 0));
        QTableWidgetItem *___qtablewidgetitem5 = tableWidget->item(3, 0);
        ___qtablewidgetitem5->setText(QApplication::translate("Spells", "Grease", 0));
        QTableWidgetItem *___qtablewidgetitem6 = tableWidget->item(4, 0);
        ___qtablewidgetitem6->setText(QApplication::translate("Spells", "Sleep", 0));
        QTableWidgetItem *___qtablewidgetitem7 = tableWidget->item(5, 0);
        ___qtablewidgetitem7->setText(QApplication::translate("Spells", "Silent Image", 0));
        QTableWidgetItem *___qtablewidgetitem8 = tableWidget->item(6, 0);
        ___qtablewidgetitem8->setText(QApplication::translate("Spells", "Chill Touch", 0));
        tableWidget->setSortingEnabled(__sortingEnabled);

        label_3->setText(QApplication::translate("Spells", "About Select Spell", 0));
        tabWidget->setTabText(tabWidget->indexOf(tabStr), QApplication::translate("Spells", "Lvl 1", 0));
        QTableWidgetItem *___qtablewidgetitem9 = tableWidget_2->horizontalHeaderItem(0);
        ___qtablewidgetitem9->setText(QApplication::translate("Spells", "Name", 0));
        QTableWidgetItem *___qtablewidgetitem10 = tableWidget_2->horizontalHeaderItem(1);
        ___qtablewidgetitem10->setText(QApplication::translate("Spells", "Learned", 0));

        const bool __sortingEnabled1 = tableWidget_2->isSortingEnabled();
        tableWidget_2->setSortingEnabled(false);
        QTableWidgetItem *___qtablewidgetitem11 = tableWidget_2->item(0, 0);
        ___qtablewidgetitem11->setText(QApplication::translate("Spells", "Jump", 0));
        QTableWidgetItem *___qtablewidgetitem12 = tableWidget_2->item(1, 0);
        ___qtablewidgetitem12->setText(QApplication::translate("Spells", "Alarm", 0));
        QTableWidgetItem *___qtablewidgetitem13 = tableWidget_2->item(2, 0);
        ___qtablewidgetitem13->setText(QApplication::translate("Spells", "Shield", 0));
        QTableWidgetItem *___qtablewidgetitem14 = tableWidget_2->item(3, 0);
        ___qtablewidgetitem14->setText(QApplication::translate("Spells", "Grease", 0));
        QTableWidgetItem *___qtablewidgetitem15 = tableWidget_2->item(4, 0);
        ___qtablewidgetitem15->setText(QApplication::translate("Spells", "Sleep", 0));
        QTableWidgetItem *___qtablewidgetitem16 = tableWidget_2->item(5, 0);
        ___qtablewidgetitem16->setText(QApplication::translate("Spells", "Silent Image", 0));
        QTableWidgetItem *___qtablewidgetitem17 = tableWidget_2->item(6, 0);
        ___qtablewidgetitem17->setText(QApplication::translate("Spells", "Chill Touch", 0));
        tableWidget_2->setSortingEnabled(__sortingEnabled1);

        label_4->setText(QApplication::translate("Spells", "About Select Spell", 0));
        tabWidget->setTabText(tabWidget->indexOf(tabDexerity), QApplication::translate("Spells", "Lvl 2", 0));
        QTableWidgetItem *___qtablewidgetitem18 = tableWidget_3->horizontalHeaderItem(0);
        ___qtablewidgetitem18->setText(QApplication::translate("Spells", "Name", 0));
        QTableWidgetItem *___qtablewidgetitem19 = tableWidget_3->horizontalHeaderItem(1);
        ___qtablewidgetitem19->setText(QApplication::translate("Spells", "Learned", 0));

        const bool __sortingEnabled2 = tableWidget_3->isSortingEnabled();
        tableWidget_3->setSortingEnabled(false);
        QTableWidgetItem *___qtablewidgetitem20 = tableWidget_3->item(0, 0);
        ___qtablewidgetitem20->setText(QApplication::translate("Spells", "Jump", 0));
        QTableWidgetItem *___qtablewidgetitem21 = tableWidget_3->item(1, 0);
        ___qtablewidgetitem21->setText(QApplication::translate("Spells", "Alarm", 0));
        QTableWidgetItem *___qtablewidgetitem22 = tableWidget_3->item(2, 0);
        ___qtablewidgetitem22->setText(QApplication::translate("Spells", "Shield", 0));
        QTableWidgetItem *___qtablewidgetitem23 = tableWidget_3->item(3, 0);
        ___qtablewidgetitem23->setText(QApplication::translate("Spells", "Grease", 0));
        QTableWidgetItem *___qtablewidgetitem24 = tableWidget_3->item(4, 0);
        ___qtablewidgetitem24->setText(QApplication::translate("Spells", "Sleep", 0));
        QTableWidgetItem *___qtablewidgetitem25 = tableWidget_3->item(5, 0);
        ___qtablewidgetitem25->setText(QApplication::translate("Spells", "Silent Image", 0));
        QTableWidgetItem *___qtablewidgetitem26 = tableWidget_3->item(6, 0);
        ___qtablewidgetitem26->setText(QApplication::translate("Spells", "Chill Touch", 0));
        tableWidget_3->setSortingEnabled(__sortingEnabled2);

        label_5->setText(QApplication::translate("Spells", "About Select Spell", 0));
        tabWidget->setTabText(tabWidget->indexOf(tabConstruction), QApplication::translate("Spells", "Lvl 3", 0));
        QTableWidgetItem *___qtablewidgetitem27 = tableWidget_4->horizontalHeaderItem(0);
        ___qtablewidgetitem27->setText(QApplication::translate("Spells", "Name", 0));
        QTableWidgetItem *___qtablewidgetitem28 = tableWidget_4->horizontalHeaderItem(1);
        ___qtablewidgetitem28->setText(QApplication::translate("Spells", "Learned", 0));

        const bool __sortingEnabled3 = tableWidget_4->isSortingEnabled();
        tableWidget_4->setSortingEnabled(false);
        QTableWidgetItem *___qtablewidgetitem29 = tableWidget_4->item(0, 0);
        ___qtablewidgetitem29->setText(QApplication::translate("Spells", "Jump", 0));
        QTableWidgetItem *___qtablewidgetitem30 = tableWidget_4->item(1, 0);
        ___qtablewidgetitem30->setText(QApplication::translate("Spells", "Alarm", 0));
        QTableWidgetItem *___qtablewidgetitem31 = tableWidget_4->item(2, 0);
        ___qtablewidgetitem31->setText(QApplication::translate("Spells", "Shield", 0));
        QTableWidgetItem *___qtablewidgetitem32 = tableWidget_4->item(3, 0);
        ___qtablewidgetitem32->setText(QApplication::translate("Spells", "Grease", 0));
        QTableWidgetItem *___qtablewidgetitem33 = tableWidget_4->item(4, 0);
        ___qtablewidgetitem33->setText(QApplication::translate("Spells", "Sleep", 0));
        QTableWidgetItem *___qtablewidgetitem34 = tableWidget_4->item(5, 0);
        ___qtablewidgetitem34->setText(QApplication::translate("Spells", "Silent Image", 0));
        QTableWidgetItem *___qtablewidgetitem35 = tableWidget_4->item(6, 0);
        ___qtablewidgetitem35->setText(QApplication::translate("Spells", "Chill Touch", 0));
        tableWidget_4->setSortingEnabled(__sortingEnabled3);

        label_6->setText(QApplication::translate("Spells", "About Select Spell", 0));
        tabWidget->setTabText(tabWidget->indexOf(tabIntelligence), QApplication::translate("Spells", "Lvl 4", 0));
        QTableWidgetItem *___qtablewidgetitem36 = tableWidget_5->horizontalHeaderItem(0);
        ___qtablewidgetitem36->setText(QApplication::translate("Spells", "Name", 0));
        QTableWidgetItem *___qtablewidgetitem37 = tableWidget_5->horizontalHeaderItem(1);
        ___qtablewidgetitem37->setText(QApplication::translate("Spells", "Learned", 0));

        const bool __sortingEnabled4 = tableWidget_5->isSortingEnabled();
        tableWidget_5->setSortingEnabled(false);
        QTableWidgetItem *___qtablewidgetitem38 = tableWidget_5->item(0, 0);
        ___qtablewidgetitem38->setText(QApplication::translate("Spells", "Jump", 0));
        QTableWidgetItem *___qtablewidgetitem39 = tableWidget_5->item(1, 0);
        ___qtablewidgetitem39->setText(QApplication::translate("Spells", "Alarm", 0));
        QTableWidgetItem *___qtablewidgetitem40 = tableWidget_5->item(2, 0);
        ___qtablewidgetitem40->setText(QApplication::translate("Spells", "Shield", 0));
        QTableWidgetItem *___qtablewidgetitem41 = tableWidget_5->item(3, 0);
        ___qtablewidgetitem41->setText(QApplication::translate("Spells", "Grease", 0));
        QTableWidgetItem *___qtablewidgetitem42 = tableWidget_5->item(4, 0);
        ___qtablewidgetitem42->setText(QApplication::translate("Spells", "Sleep", 0));
        QTableWidgetItem *___qtablewidgetitem43 = tableWidget_5->item(5, 0);
        ___qtablewidgetitem43->setText(QApplication::translate("Spells", "Silent Image", 0));
        QTableWidgetItem *___qtablewidgetitem44 = tableWidget_5->item(6, 0);
        ___qtablewidgetitem44->setText(QApplication::translate("Spells", "Chill Touch", 0));
        tableWidget_5->setSortingEnabled(__sortingEnabled4);

        label_7->setText(QApplication::translate("Spells", "About Select Spell", 0));
        tabWidget->setTabText(tabWidget->indexOf(tabWizdom), QApplication::translate("Spells", "Lvl 5", 0));
        QTableWidgetItem *___qtablewidgetitem45 = tableWidget_6->horizontalHeaderItem(0);
        ___qtablewidgetitem45->setText(QApplication::translate("Spells", "Name", 0));
        QTableWidgetItem *___qtablewidgetitem46 = tableWidget_6->horizontalHeaderItem(1);
        ___qtablewidgetitem46->setText(QApplication::translate("Spells", "Learned", 0));

        const bool __sortingEnabled5 = tableWidget_6->isSortingEnabled();
        tableWidget_6->setSortingEnabled(false);
        QTableWidgetItem *___qtablewidgetitem47 = tableWidget_6->item(0, 0);
        ___qtablewidgetitem47->setText(QApplication::translate("Spells", "Jump", 0));
        QTableWidgetItem *___qtablewidgetitem48 = tableWidget_6->item(1, 0);
        ___qtablewidgetitem48->setText(QApplication::translate("Spells", "Alarm", 0));
        QTableWidgetItem *___qtablewidgetitem49 = tableWidget_6->item(2, 0);
        ___qtablewidgetitem49->setText(QApplication::translate("Spells", "Shield", 0));
        QTableWidgetItem *___qtablewidgetitem50 = tableWidget_6->item(3, 0);
        ___qtablewidgetitem50->setText(QApplication::translate("Spells", "Grease", 0));
        QTableWidgetItem *___qtablewidgetitem51 = tableWidget_6->item(4, 0);
        ___qtablewidgetitem51->setText(QApplication::translate("Spells", "Sleep", 0));
        QTableWidgetItem *___qtablewidgetitem52 = tableWidget_6->item(5, 0);
        ___qtablewidgetitem52->setText(QApplication::translate("Spells", "Silent Image", 0));
        QTableWidgetItem *___qtablewidgetitem53 = tableWidget_6->item(6, 0);
        ___qtablewidgetitem53->setText(QApplication::translate("Spells", "Chill Touch", 0));
        tableWidget_6->setSortingEnabled(__sortingEnabled5);

        label_8->setText(QApplication::translate("Spells", "About Select Spell", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("Spells", "Lvl 6", 0));
        QTableWidgetItem *___qtablewidgetitem54 = tableWidget_7->horizontalHeaderItem(0);
        ___qtablewidgetitem54->setText(QApplication::translate("Spells", "Name", 0));
        QTableWidgetItem *___qtablewidgetitem55 = tableWidget_7->horizontalHeaderItem(1);
        ___qtablewidgetitem55->setText(QApplication::translate("Spells", "Learned", 0));

        const bool __sortingEnabled6 = tableWidget_7->isSortingEnabled();
        tableWidget_7->setSortingEnabled(false);
        QTableWidgetItem *___qtablewidgetitem56 = tableWidget_7->item(0, 0);
        ___qtablewidgetitem56->setText(QApplication::translate("Spells", "Jump", 0));
        QTableWidgetItem *___qtablewidgetitem57 = tableWidget_7->item(1, 0);
        ___qtablewidgetitem57->setText(QApplication::translate("Spells", "Alarm", 0));
        QTableWidgetItem *___qtablewidgetitem58 = tableWidget_7->item(2, 0);
        ___qtablewidgetitem58->setText(QApplication::translate("Spells", "Shield", 0));
        QTableWidgetItem *___qtablewidgetitem59 = tableWidget_7->item(3, 0);
        ___qtablewidgetitem59->setText(QApplication::translate("Spells", "Grease", 0));
        QTableWidgetItem *___qtablewidgetitem60 = tableWidget_7->item(4, 0);
        ___qtablewidgetitem60->setText(QApplication::translate("Spells", "Sleep", 0));
        QTableWidgetItem *___qtablewidgetitem61 = tableWidget_7->item(5, 0);
        ___qtablewidgetitem61->setText(QApplication::translate("Spells", "Silent Image", 0));
        QTableWidgetItem *___qtablewidgetitem62 = tableWidget_7->item(6, 0);
        ___qtablewidgetitem62->setText(QApplication::translate("Spells", "Chill Touch", 0));
        tableWidget_7->setSortingEnabled(__sortingEnabled6);

        label_9->setText(QApplication::translate("Spells", "About Select Spell", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("Spells", "Lvl 7", 0));
        QTableWidgetItem *___qtablewidgetitem63 = tableWidget_8->horizontalHeaderItem(0);
        ___qtablewidgetitem63->setText(QApplication::translate("Spells", "Name", 0));
        QTableWidgetItem *___qtablewidgetitem64 = tableWidget_8->horizontalHeaderItem(1);
        ___qtablewidgetitem64->setText(QApplication::translate("Spells", "Learned", 0));

        const bool __sortingEnabled7 = tableWidget_8->isSortingEnabled();
        tableWidget_8->setSortingEnabled(false);
        QTableWidgetItem *___qtablewidgetitem65 = tableWidget_8->item(0, 0);
        ___qtablewidgetitem65->setText(QApplication::translate("Spells", "Jump", 0));
        QTableWidgetItem *___qtablewidgetitem66 = tableWidget_8->item(1, 0);
        ___qtablewidgetitem66->setText(QApplication::translate("Spells", "Alarm", 0));
        QTableWidgetItem *___qtablewidgetitem67 = tableWidget_8->item(2, 0);
        ___qtablewidgetitem67->setText(QApplication::translate("Spells", "Shield", 0));
        QTableWidgetItem *___qtablewidgetitem68 = tableWidget_8->item(3, 0);
        ___qtablewidgetitem68->setText(QApplication::translate("Spells", "Grease", 0));
        QTableWidgetItem *___qtablewidgetitem69 = tableWidget_8->item(4, 0);
        ___qtablewidgetitem69->setText(QApplication::translate("Spells", "Sleep", 0));
        QTableWidgetItem *___qtablewidgetitem70 = tableWidget_8->item(5, 0);
        ___qtablewidgetitem70->setText(QApplication::translate("Spells", "Silent Image", 0));
        QTableWidgetItem *___qtablewidgetitem71 = tableWidget_8->item(6, 0);
        ___qtablewidgetitem71->setText(QApplication::translate("Spells", "Chill Touch", 0));
        tableWidget_8->setSortingEnabled(__sortingEnabled7);

        label_10->setText(QApplication::translate("Spells", "About Select Spell", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("Spells", "Lvl 8", 0));
        QTableWidgetItem *___qtablewidgetitem72 = tableWidget_9->horizontalHeaderItem(0);
        ___qtablewidgetitem72->setText(QApplication::translate("Spells", "Name", 0));
        QTableWidgetItem *___qtablewidgetitem73 = tableWidget_9->horizontalHeaderItem(1);
        ___qtablewidgetitem73->setText(QApplication::translate("Spells", "Learned", 0));

        const bool __sortingEnabled8 = tableWidget_9->isSortingEnabled();
        tableWidget_9->setSortingEnabled(false);
        QTableWidgetItem *___qtablewidgetitem74 = tableWidget_9->item(0, 0);
        ___qtablewidgetitem74->setText(QApplication::translate("Spells", "Jump", 0));
        QTableWidgetItem *___qtablewidgetitem75 = tableWidget_9->item(1, 0);
        ___qtablewidgetitem75->setText(QApplication::translate("Spells", "Alarm", 0));
        QTableWidgetItem *___qtablewidgetitem76 = tableWidget_9->item(2, 0);
        ___qtablewidgetitem76->setText(QApplication::translate("Spells", "Shield", 0));
        QTableWidgetItem *___qtablewidgetitem77 = tableWidget_9->item(3, 0);
        ___qtablewidgetitem77->setText(QApplication::translate("Spells", "Grease", 0));
        QTableWidgetItem *___qtablewidgetitem78 = tableWidget_9->item(4, 0);
        ___qtablewidgetitem78->setText(QApplication::translate("Spells", "Sleep", 0));
        QTableWidgetItem *___qtablewidgetitem79 = tableWidget_9->item(5, 0);
        ___qtablewidgetitem79->setText(QApplication::translate("Spells", "Silent Image", 0));
        QTableWidgetItem *___qtablewidgetitem80 = tableWidget_9->item(6, 0);
        ___qtablewidgetitem80->setText(QApplication::translate("Spells", "Chill Touch", 0));
        tableWidget_9->setSortingEnabled(__sortingEnabled8);

        label_11->setText(QApplication::translate("Spells", "About Select Spell", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_4), QApplication::translate("Spells", "Lvl 9", 0));
        lblTitle->setText(QApplication::translate("Spells", "Spells", 0));
        label_2->setText(QApplication::translate("Spells", "0000", 0));
        label->setText(QApplication::translate("Spells", "Spell Points Remaining:", 0));
        btnAboutClasses->setText(QApplication::translate("Spells", "About Spells", 0));
    } // retranslateUi

};

namespace Ui {
    class Spells: public Ui_Spells {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SPELLS_H
